EN_KEYS_312 = [
    ('snSignOutAllDevices', 'Sign Out All Devices'),
    ('snSignOutAllConfirm', 'This will sign you out of all active sessions except this one.'),
    ('snSignOutAll', 'Sign Out All'),
    ('snAllRevoked', 'All other sessions revoked'),
    ('snFailedRevokeAll', 'Failed to revoke sessions'),
    ('snRevoked', 'Session revoked'),
    ('snFailedRevoke', 'Failed to revoke session'),
    ('snTitle', 'Active Sessions'),
    ('snNoActiveSessions', 'No active sessions'),
    ('snUnknown', 'Unknown'),
    ('snCurrent', 'Current'),
    ('snRevoke', 'Revoke'),
    ('bioSetupTitle', 'Biometric Setup'),
    ('bioSetupSubtitle', 'Use your fingerprint or face to sign in quickly and securely.'),
    ('bioSetupRegister', 'Register this device'),
    ('bioSetupDeviceNameLabel', 'Device name (e.g. My Phone)'),
    ('bioSetupDeviceNameDefault', 'My Device'),
    ('bioSetupRegistered', 'Device registered'),
    ('bioSetupRegistrationFailed', 'Registration failed'),
    ('bioSetupRegisteredDevices', 'Registered Devices'),
    ('bioSetupUnknown', 'Unknown'),
    ('mnMarkAllFailed', 'Could not mark notifications as read.'),
    ('mnNoDestination', 'This notification has no linked destination yet.'),
    ('mnTitle', 'Notification'),
    ('mnSettings', 'Notification settings'),
    ('mnMarking', 'Marking...'),
    ('mnMarkAllRead', 'Mark all as read'),
    ('mnGranularHint', 'Granular controls live inside each service update.'),
    ('mnTabAll', 'All'),
    ('mnTabBookings', 'Bookings'),
    ('mnTabOffers', 'Offers'),
    ('mnTabSystem', 'System'),
    ('mnEmptyBookings', 'Booking updates will land here as providers respond.'),
    ('mnEmptyOffers', 'Promos and special offers will show up here.'),
    ('mnEmptySystem', 'System updates will appear here when available.'),
    ('mnOpenDetails', 'Open this update to see more details.'),
    ('mnMinutesAgo', '{minutes}m ago'),
    ('@mnMinutesAgo', '{"placeholders": {"minutes": {}}}'),
    ('mnHoursAgo', '{hours}h ago'),
    ('@mnHoursAgo', '{"placeholders": {"hours": {}}}'),
    ('mnDaysAgo', '{days}d ago'),
    ('@mnDaysAgo', '{"placeholders": {"days": {}}}'),
    ('callPermTitleVideo', 'Camera & Microphone'),
    ('callPermTitleAudio', 'Microphone'),
    ('callPermAllowBoth', 'Allow camera & microphone'),
    ('callPermAllowMic', 'Allow microphone'),
    ('callPermCalling', 'Calling {name}'),
    ('@callPermCalling', '{"placeholders": {"name": {}}}'),
    ('callPermAllow', 'Allow'),
    ('chdUnknown', 'Unknown'),
    ('chdTitle', 'Call Details'),
    ('chdUnknownProvider', 'Unknown Provider'),
    ('chdInfoTitle', 'Call Information'),
    ('chdStatus', 'Status'),
    ('chdDuration', 'Duration'),
    ('chdDateTitle', 'Date & Time'),
    ('chdCallBack', 'Call Back'),
    ('chdMessage', 'Message'),
]

FIL_KEYS_312 = [
    ('snSignOutAllDevices', 'Mag-sign Out sa Lahat ng Device'),
    ('snSignOutAllConfirm', 'Magre-revoke ito sa iyo sa lahat ng aktibong session maliban sa isa na ito.'),
    ('snSignOutAll', 'Mag-sign Out sa Lahat'),
    ('snAllRevoked', 'Na-revoke ang lahat ng ibang session'),
    ('snFailedRevokeAll', 'Hindi na-revoke ang mga session'),
    ('snRevoked', 'Na-revoke ang session'),
    ('snFailedRevoke', 'Hindi na-revoke ang session'),
    ('snTitle', 'Mga Aktibong Session'),
    ('snNoActiveSessions', 'Walang aktibong session'),
    ('snUnknown', 'Hindi kilala'),
    ('snCurrent', 'Kasalukuyan'),
    ('snRevoke', 'I-revoke'),
    ('bioSetupTitle', 'Biometric Setup'),
    ('bioSetupSubtitle', 'Gamitin ang iyong fingerprint o mukha para mag-sign in nang mabilis at ligtas.'),
    ('bioSetupRegister', 'I-register ang device na ito'),
    ('bioSetupDeviceNameLabel', 'Pangalan ng device (hal. Telepono Ko)'),
    ('bioSetupDeviceNameDefault', 'Device Ko'),
    ('bioSetupRegistered', 'Nakarehistro ang device'),
    ('bioSetupRegistrationFailed', 'Hindi nakarehistro'),
    ('bioSetupRegisteredDevices', 'Mga Nakarehistrong Device'),
    ('bioSetupUnknown', 'Hindi kilala'),
    ('mnMarkAllFailed', 'Hindi ma-mark bilang nabasa ang mga abiso.'),
    ('mnNoDestination', 'Wala pang linked destination ang abisong ito.'),
    ('mnTitle', 'Notifications'),
    ('mnSettings', 'Mga setting ng abiso'),
    ('mnMarking', 'Binibigyan ng marka...'),
    ('mnMarkAllRead', 'Markahan lahat bilang nabasa'),
    ('mnGranularHint', 'Nasa loob ng bawat service update ang mga mas detalyadong kontrol.'),
    ('mnTabAll', 'Lahat'),
    ('mnTabBookings', 'Mga Booking'),
    ('mnTabOffers', 'Mga Offer'),
    ('mnTabSystem', 'System'),
    ('mnEmptyBookings', 'Dadating dito ang mga update sa booking habang sumasagot ang mga provider.'),
    ('mnEmptyOffers', 'Dito lalabas ang mga promo at espesyal na offer.'),
    ('mnEmptySystem', 'Dito lalabas ang mga system update kapag available.'),
    ('mnOpenDetails', 'Buksan ang update na ito para makita ang karagdagang detalye.'),
    ('mnMinutesAgo', '{minutes}m ang nakalipas'),
    ('mnHoursAgo', '{hours}h ang nakalipas'),
    ('mnDaysAgo', '{days}a ang nakalipas'),
    ('callPermTitleVideo', 'Camera at Microphone'),
    ('callPermTitleAudio', 'Microphone'),
    ('callPermAllowBoth', 'Payagan ang camera at microphone'),
    ('callPermAllowMic', 'Payagan ang microphone'),
    ('callPermCalling', 'Tumatawag kay {name}'),
    ('callPermAllow', 'Payagan'),
    ('chdUnknown', 'Hindi kilala'),
    ('chdTitle', 'Detalye ng Tawag'),
    ('chdUnknownProvider', 'Hindi Kilalang Provider'),
    ('chdInfoTitle', 'Impormasyon ng Tawag'),
    ('chdStatus', 'Katayuan'),
    ('chdDuration', 'Tagal'),
    ('chdDateTitle', 'Petsa at Oras'),
    ('chdCallBack', 'Tumawag Muli'),
]
