# Allocate RAM and garbage collection properties
org.gradle.jvmargs=-Xmx6G -XX:+UseG1GC -XX:MaxMetaspaceSize=1G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError

# Core AndroidX support
android.useAndroidX=true

# Keep compiler processes alive to avoid cold start times
org.gradle.daemon=true

# Compile independent modules side-by-side simultaneously
org.gradle.parallel=true

# Enable the Gradle configuration cache for faster subsequent builds
org.gradle.configuration-cache=false

# Enable build caching to reuse outputs from previous builds
org.gradle.caching=true

# Optimize Kotlin daemon execution
kotlin.incremental=false
# This builtInKotlin flag was added automatically by Flutter migrator
android.builtInKotlin=false
# This newDsl flag was added automatically by Flutter migrator
android.newDsl=false
